#! /bin/sh

## We embed the libtool dependencies in the repository, so don't
## call libtoolize automatically here.  Only if it is defined.

: ${LIBTOOLIZE=true}
export LIBTOOLIZE

autoreconf -f -v -i
