#! /bin/sh

# bootstrap might bring some files in these directories.
mkdir -p build-aux/m4

## Don't run autoheader, use jconfig.cfg as is.
: ${AUTOHEADER=true}
export AUTOHEADER

## Do run libtoolize, in spite of what bootstrap from Urbi might say.
case $LIBTOOLIZE in
  (true) unset LIBTOOLIZE
esac

autoreconf -f -v -i
